import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Index.module.css'
import { getData } from '@/src/data';
import { useEffect, useState } from 'react';
import Order from '@/src/islands/Order';

export default function Home() {
  return (
    <>
      <Head>
        <title>Donkenrun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Order />
      </main>
    </>
  )
}
