import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Index.module.css'
import { getData } from '@/src/data';
import { useEffect, useState } from 'react';
import Order from '@/src/islands/Order';
import { useSession, signIn, signOut } from "next-auth/react"
import Button from '@/src/components/Button';

export default function Home() {
  const { data: session } = useSession()
  return (
    <>
      <Head>
        <title>Donkenrun</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { session ?
        <main className={styles.main}>
          <Order />
        </main> :
        <main className={styles.login}>
          <h1>
            Donkenrun 2023
          </h1>
          <Button onClick={() => signIn()}>Sign in</Button>
        </main>
      }
    </>
  )
}
