import React from 'react'
import { useSession, signIn, signOut } from "next-auth/react"
import PurchasePage from '@/src/component/purchase'
import { Button } from '@mui/material'
import Head from 'next/head'

const index = () => {
    const { data: session } = useSession()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                session && session.user ?
                <PurchasePage /> :
                <div>
                    <h1>
                        mcdonal
                    </h1>
                    <Button onClick={() => signIn()}>Sign in</Button>
                </div>
            }
        </>
    )
}

export default index